name: CI
on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: gh-linux-arm64-16cpu
    permissions:
      id-token: write
      contents: read
    env:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v4
      - run: bazel fetch //...
      - run: bazel build //...
      - run: bazel build @pip//...
